### ISSUE TITLE
Key过期了，没法测试

### ISSUE THREAD

**Issue by yecoco** [tsingsee/EasyPlayer-RTMP-iOS#1]
Key过期了，没法测试

**Comment by leo-09** [comment]
已经在处理了，可以加我微信18855117272------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;YeCc&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月12日(星期四) 上午10:43
收件人:&nbsp;&quot;tsingsee/EasyPlayer-RTMP-iOS&quot;<EasyPlayer-RTMP-iOS@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[tsingsee/EasyPlayer-RTMP-iOS] Key过期了，没法测试 (#1)

**Comment by leo-09** [comment]
过期后会及时更新的，请保持关注。也可以加我微信18855117272
