### ISSUE TITLE
激活码过期了无法测试

### ISSUE THREAD

**Issue by MoDaBao** [tsingsee/EasyPlayer-RTMP-iOS#2]

**Comment by leo-09** [comment]
可以加我QQ2779005381




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tsingsee/EasyPlayer-RTMP-iOS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 下午5:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tsingsee/EasyPlayer-RTMP-iOS] 激活码过期了无法测试 (Issue #2)
